### ISSUE TITLE
页面内容被底部导航栏凸出空白遮档

### ISSUE THREAD

**Issue by 12366** [hanlin19900610/flutter_bottom_navigation_bar#1]
页面内容与底部导航栏有50像素空白间距

**Comment by hanlin19900610** [comment]
最近比较忙, 刚抽出时间修改这个问题, 刚开始只是为了实现一个凸起按钮的效果,并没有考虑到页面,

**Comment by halower** [comment]
如果底部是5个按钮好像，字体颜色都成白色了

**Comment by gendseo** [comment]
@halower 将type设置为BottomNavigationBarType.fixed
